#!/bin/sh /etc/rc.common

START=90
STOP=1
USE_PROCD=1

PROG=/usr/bin/ha_device_tracker.sh
CONFIG_FILE="/etc/config/ha_device_tracker"

start_service() {
    # Check if enabled in UCI config before starting
    local enabled
    config_load ha_device_tracker
    config_get_bool enabled settings enabled '0'

    if [ "$enabled" -ne 1 ]; then
        echo "Home Assistant Device Tracker is disabled in $CONFIG_FILE."
        return 1
    fi

    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn # Restart if it crashes
    # Optionally, forward stdout/stderr to logd:
    # procd_set_param stdout 1
    # procd_set_param stderr 1
    procd_set_param file "$CONFIG_FILE" # Restart service if this config file changes and 'reload_config' is called
    procd_close_instance
}

reload_service() {
    stop
    start
}

service_triggers() {
    procd_add_reload_trigger "ha_device_tracker"
}